project_name: baseclass
builds:
  - main: ./baseclass/cmd/baseclass
    ldflags:
      - -s -w -X github.com/baseclass/cli/baseclass/version.Version={{.Tag}} -X github.com/baseclass/cli/baseclass/version.Date={{.Date}} -X github.com/baseclass/cli/baseclass/version.Head={{.FullCommit}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
